bin/magento module:disable \
Magento_Paypal \
Magento_PaypalGraphQl \
Magento_ReCaptchaPaypal \
Magento_PaypalCaptcha \
PayPal_Braintree \
PayPal_BraintreeGraphQl \
Amazon_Core \
Amazon_Login \
Amazon_Payment \
Temando_ShippingRemover \
Yotpo_Yotpo \
Magento_AdobeIms \
Magento_AdobeImsApi \
Magento_AdobeStockAdminUi \
Magento_AdobeStockAssetApi \
Magento_AdobeStockClient \
Magento_AdobeStockClientApi \
Magento_AdobeStockImage \
Magento_AdobeStockImageApi \
Magento_AdobeStockAsset \
Magento_AdobeStockImageAdminUi \
Klarna_Core \
Klarna_Ordermanagement \
Klarna_Kp \
Klarna_Onsitemessaging \
Klarna_KpGraphQl \
Magento_AwsS3 \
Magento_AwsS3PageBuilder \
Magento_CatalogPageBuilderAnalytics \
Magento_CmsPageBuilderAnalytics \
Magento_PageBuilder \
Magento_PageBuilderAnalytics \
Magento_PageBuilderAdminAnalytics \
Magento_AwsS3PageBuilder \
Dotdigitalgroup_Email \
Dotdigitalgroup_Chat \
Dotdigitalgroup_ChatGraphQl \
Dotdigitalgroup_EmailGraphQl \
Dotdigitalgroup_Sms \
Magento_Dhl \
Magento_Fedex \
Magento_GoogleAdwords \
Magento_Marketplace \
Magento_Rss \
Magento_Elasticsearch7 \
Magento_Elasticsearch6 \
Magento_Ups \
Magento_SampleData \
Magento_Usps
